### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by dumpWhale** [angr/rex#18]
I ran into a problem while running the given test cases——test_linux_stacksmash():
   tracer.tracer.TracerMisfollowError: program did not behave correctly, expected only one path

Is it a code problem or is it my configuration problem?

Hoping for your reply, thanks.

**Comment by carterMgj** [comment]
I meet the same problem, too.   I use the shellphish/mechaphish docker. Do you use the docker, too ?

**Comment by dumpWhale** [comment]
no I just download the codes in the angr，shellphish as well as mechaphish
