### ISSUE TITLE
`test_linux_network_stacksmash_64` is failing in CI

### ISSUE THREAD

**Issue by twizmwazin** [angr/rex#99]
### Description

`test_linux_network_stacksmash_64` is failing in CI frequently for the past couple weeks.

**Comment by Kyle-Kyle** [comment]
closed as we are not seeing it recently

**Comment by Kyle-Kyle** [comment]
I cannot reproduce it locally. But according to the log (desync in tracer), I suspect it has something to do with qtrace.

**Comment by mborgerson** [comment]
@Kyle-Kyle I did not investigate deeply, but it seems related to the recent upgrade to Python 3.12 in CI. Did you try with Python 3.12 locally?
